version: '2.3'

services:
  consul:
    image: autopilotpattern/consul:1.0.0r43
    command: >
      /usr/local/bin/containerpilot
    env_file:
      - .consul.env
    restart: always
    mem_limit: 512m
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-consul
    ports:
      - 9090
      - 8500

  navigation:
    image: joyent/webconsole-navigation:1.0.0
    restart: always
    mem_limit: 1g
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-navigation
    env_file:
      - .env
      - .consul.env
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/app/data:ro
