version: '2.3'

services:
  navigation:
    image: joyent/webconsole-navigation:1.0.0
    restart: always
    mem_limit: 1g
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-navigation
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/app/data:ro
