version: '2.3'

services:
  navigation:
    build: ./
    restart: always
    mem_limit: 1g
    env_file:
      - .env
    environment:
      - PORT=8080
      - BASE_URL=http://localhost
      - NODE_ENV=development
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=0
      - SSO_URL=https://sso.joyent.com/login
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/app/data:ro
