consul:
  image: autopilotpattern/consul:1.0.0r43
  command: >
    /usr/local/bin/containerpilot
  environment:
   - CONSUL_DEV=1
   - CONSUL=consul
  restart: always
  mem_limit: 512m
  ports:
    - 9090:9090
    - 8500:8500

webconsole-console:
  build: ./
  restart: always
  mem_limit: 1g
  environment:
    - CONSUL=CONSUL
    - PORT=8080
  links:
    - consul:consul
  ports:
    - 8080:8080
